language: php

dist: trusty
php:
    - '7.0'
    - nightly

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

matrix:
    include:
        - php: '5.2'
          dist: precise
        - php: '5.3'
          dist: precise

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit